--Create Orders
CREATE TABLE ORDERS 
(
  ID NUMBER(*, 0) NOT NULL 
, USERID NUMBER(*, 0) 
, GOODID NUMBER(*, 0) 
, ISPAYED NUMBER(*, 0) 
, CONSTRAINT ORDERS_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ORDERS_PK ON ORDERS (ID ASC) 
      LOGGING 
      TABLESPACE "SONOWEB_DATA" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        PCTINCREASE 0 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SONOWEB_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_GOODS FOREIGN KEY
(
  GOODID 
)
REFERENCES GOODS
(
  ID 
)
ENABLE;

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_USERS FOREIGN KEY
(
  USERID 
)
REFERENCES USERS
(
  ID 
)
ENABLE;

CREATE SEQUENCE ORDERS_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE TRIGGER ORDERS_TRG 
BEFORE INSERT ON ORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT ORDERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/